name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
        laravel: ['10', '11', '12', '13']
        exclude:
          - php: '8.1'
            laravel: '11'
          - php: '8.1'
            laravel: '12'
          - php: '8.1'
            laravel: '13'
          - php: '8.2'
            laravel: '13'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Laravel 10
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:^10.50.1" "phpunit/phpunit:^10.5.63" --no-update --no-interaction
        if: "matrix.laravel == '10'"

      - name: Select Laravel 11
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:^11.50.0" "phpunit/phpunit:^10.5.63" --no-update --no-interaction
        if: "matrix.laravel == '11'"

      - name: Select Laravel 12
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:^12.55.1" "phpunit/phpunit:^11.5.55" --no-update --no-interaction
        if: "matrix.laravel == '12'"

      - name: Select Laravel 13
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "laravel/framework:^13.1.1" "phpunit/phpunit:^12.5.14" --no-update --no-interaction
        if: "matrix.laravel == '13'"

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
